spring:
  profiles:
    active:
    - dev  
---
server:
  port: 8001
#
#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
#  type-aliases-package: com.dz.springcloud.entities         # 所有Entity别名类所在包
#  mapper-locations:
#  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.dz.ztsys.entities  # 注意：对应实体类的路径
  global-config:
    id-type: 0  # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性      
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql
    
spring:
  profiles: dev
  application:
    name: family-provider
  datasource:
         #### MYSQL数据库方式 #####
        name: test
        url: jdbc:mysql://127.0.0.1:3306/genealogy_master
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
  thymeleaf: 
      cache: false  
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://localhost:3306/cloudDB01
#    username: root
#    password: root
#    dbcp2:
#      min-idle: 5
#      initial-size: 5
#      max-total: 5
#      max-wait-millis: 200

            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: family-provider-8001
    prefer-ip-address: true
    
info: 
  app.name: dz-microservicecloud-config01
  company.name: www.ztsys.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
###################  自定义项目配置 ###################
dz:
  excel-path: D:/home/
  files-path: D:/home/
  files-url-prefix: https://show.dz.net/files/ # 文件访问URL前缀
  pics-path: D:/home/
  pics-url-prefix: https://show.dz.net/pics/ # 图片访问URL前缀
  posapi-url-prefix: http://127.0.0.1:9095